---
title: "/usr/bin/time comparison of fastp thread changes"
execute:
  echo: false
  eval: true
format: html
editor:
  markdown:
    wrap: 80
---
```{r}
#load libraries
library(tidyverse)
library(ggpubr)
library(patchwork)
library(dplyr)
library(ggrepel)
library(ggpattern)
library(patchwork)
```

```{r}
# load files
filenames <- list.files("../../dl_project_files/results_TruthfulQA/", recursive = TRUE, full.names = TRUE, pattern = '.csv$')

filenames


filenames_truth <- list.files("../../dl_project_files/results_TruthfulQA_fulltruth/", recursive = TRUE, full.names = TRUE, pattern = '.csv$')

filenames_truth
```



```{r}
process_file <- function(file_path, truthful = FALSE) {
  if (truthful) {
      `Merged models` <- str_match(file_path, "TruthfulQA_fulltruth\\/(?:results)_([^_]+)_ZeroShot_TruthfulQA_EN.csv")[2]
      data <- read.csv(file_path)
      data <- data |>
      mutate(`Merged models` = `Merged models`)
  } else {
      `Merged models` <- str_match(file_path, "TruthfulQA\\/(?:results)_([^_]+)_ZeroShot_TruthfulQA_EN.csv")[2]
      data <- read.csv(file_path)
      data <- data |>
      mutate(`Merged models` = `Merged models`)
  }
  return(data)
}


result_list <- lapply(filenames, process_file)
result_list_truth <- lapply(filenames_truth, process_file, truthful = TRUE)

result_list
result_list_truth
```


```{r}
combined_data <- bind_rows(result_list, .id = "source") |>
  filter(category != "Statistics") |>
  rename(`Merged models` = `Merged models`)

combined_data_truth <- bind_rows(result_list_truth, .id = "source") |>
  filter(category != "Statistics") |>
  rename(`Merged models` = `Merged models`)
```

```{r}
filenames_instruct <- combined_data |>
  select(`Merged models`) |>
  unique() |>
  filter(str_detect(`Merged models`, "biomistral-instruct")) |>
  pull()

filenames_internist <- combined_data |>
  select(`Merged models`) |>
  unique() |>
  filter(str_detect(`Merged models`, "internistai-biomistral")) |>
  pull()

filenames_single <- combined_data |>
  select(`Merged models`) |>
  unique() |>
  filter(str_detect(`Merged models`, "BioMistral-7B-Instruct") |
           str_detect(`Merged models`, "internistai-7b") |
           str_detect(`Merged models`, "Mistral-7B")) |>
  pull()

filenames_instruct
filenames_internist
filenames_single
```


```{r}
filenames_instruct_truth <- combined_data_truth |>
  select(`Merged models`) |>
  unique() |>
  filter(str_detect(`Merged models`, "biomistral-instruct")) |>
  pull()

filenames_internist_truth <- combined_data_truth |>
  select(`Merged models`) |>
  unique() |>
  filter(str_detect(`Merged models`, "internistai-biomistral")) |>
  pull()

filenames_single_truth <- combined_data_truth |>
  select(`Merged models`) |>
  unique() |>
  filter(str_detect(`Merged models`, "BioMistral-7B-Instruct") |
           str_detect(`Merged models`, "internistai-7b") |
           str_detect(`Merged models`, "Mistral-7B")) |>
  pull()

filenames_instruct_truth
filenames_internist_truth
filenames_single_truth
```




```{r}
# SINGLE PLOT
create_plot_combined <- function(data_name, data_tibble, title_text, subtitle_text) {

  plot_obj <- data_tibble |>
      mutate(correct = ifelse(correct_letter == best_prediction, 1, 0)) |>
      filter(`Merged models` %in% data_name) |>
      mutate(correct_percent = correct*100) |>
      group_by(category) |>
      ungroup() |>
      ggbarplot(x = "category", y = "correct_percent", fill = "Merged models", alpha = 0.2,
              x.text.angle = 35,
              lab.vjust = 2,
              height = 0.5,
              xlab = "Category",
              ylab = "Truthfulness",
              lab.nb.digits = 1,
              palette = "Dark2",
              position = position_dodge(0.85),
              add = c("mean"),
              label = TRUE, lab.size = 2) + theme(axis.text.x = element_text(size = 8)) + 
    theme(legend.text = element_text(size = 6), 
          legend.title = element_text(size = 6), 
          legend.key.size = unit(0.5, 'cm'),
          legend.position = "left",
          plot.margin = unit(c(0, 0, 0, 0), 
                                "inches")) +
  guides(fill = guide_legend(nrow = 6)) +
    plot_annotation(title = title_text,
                           subtitle = subtitle_text)  &
      theme(plot.subtitle = element_text(size = 10)) 
  
    return(plot_obj)

}

```

```{r}
# Not truthful data
internist_merge_plot <- create_plot_combined(data_name = filenames_internist,
                     data_tibble = combined_data,
                     title_text = "",
                     subtitle_text = "")
# title_text = "Truthfulness (correctly predicted letter %) per category - QA prompts",
#                      subtitle_text = "BioMistral-7B-v0.1 and Internist.ai-7b merged with SLERP, TIES, and DARE-TIES")

instruct_merge_plot <- create_plot_combined(data_name =  filenames_instruct,
                     data_tibble = combined_data,
                     title_text = "",
                     subtitle_text = "")

                     # title_text = "Truthfulness (correctly predicted letter %) per category - QA prompts",
                     # subtitle_text = "Mistral-7B-Instruct (v0.1 and v0.2) and BioMistral-7B-v0.1 merged with SLERP, TIES, and DARE-TIES")

single_model_plot <- create_plot_combined(data_name = filenames_single,
                     data_tibble = combined_data,
                     title_text = "",
                     subtitle_text = "")


                     # title_text = "Truthfulness (correctly predicted letter %) per category - QA prompts",
                     # subtitle_text = "Mistral-7B-Instruct (v0.1 and v0.2), BioMistral-7B-v0.1, internistai-7b-v0.2 (no merging)")
```




```{r}
internist_merge_truth_plot <- create_plot_combined(data_name = filenames_internist_truth,
                     data_tibble = combined_data_truth,
                     title_text = "",
                     subtitle_text = "")
# Truthfulness (correctly predicted letter %) per category with - Truthful Prompts
# BioMistral-7B-v0.1 and Internist.ai-7b merged with SLERP, TIES, and DARE-TIES

instruct_merge_truth_plot <- create_plot_combined(data_name =  filenames_instruct_truth,
                     data_tibble = combined_data_truth,
                     title_text = "",
                     subtitle_text = "")

# "Truthfulness (correctly predicted letter %) per category - Truthful Prompts",
# subtitle_text = "Mistral-7B-Instruct (v0.1 and v0.2) and BioMistral-7B-v0.1 merged with SLERP, TIES, and DARE-TIES"

single_model_truth_plot <- create_plot_combined(data_name = filenames_single_truth,
                     data_tibble = combined_data_truth,
                     title_text = "",
                     subtitle_text = "")


                     # title_text = "Truthfulness (correctly predicted letter %) per category - Truthful Prompts",
                     # subtitle_text = "Mistral-7B-Instruct (v0.1 and v0.2), BioMistral-7B-v0.1, internistai-7b-v0.2 (no merging)"
```
```{r}

single_model_plot
single_model_truth_plot
instruct_merge_plot
instruct_merge_truth_plot
internist_merge_plot
internist_merge_truth_plot


```

```{r}
ggsave(paste("single_model_plot", ".eps"), single_model_plot, device = cairo_ps, units = c("px"),
  dpi = 300)
ggsave(paste("single_model_truth_plot", ".eps"), single_model_truth_plot, device = cairo_ps, units = c("px"),
  dpi = 300)
ggsave(paste("instruct_merge_plot", ".eps"), instruct_merge_plot, device = cairo_ps, units = c("px"),
  dpi = 300)
ggsave(paste("instruct_merge_truth_plot", ".eps"), instruct_merge_truth_plot, device = cairo_ps, units = c("px"),
  dpi = 300)
ggsave(paste("internist_merge_plot", ".eps"), internist_merge_plot, device = cairo_ps, units = c("px"),
  dpi = 300)
ggsave(paste("internist_merge_truth_plot", ".eps"), internist_merge_truth_plot, device = cairo_ps, units = c("px"),
  dpi = 300)


```
